# .github/marketplace/metadata.yml
name: AI Code Reviewer
description: >
  AI-powered code review automation for GitHub pull requests using configurable AI models and reviewer personas.
pricing_tiers:
  - type: FREE
categories:
  - code-review
  - continuous-integration
  - ai-tools
branding:
  icon: "icon.png"
  color: "blue"
long_description: |
  🚀 **AI Code Reviewer** brings AI-driven code review automation into your development workflow.

  🤖 **Features:**
  - Multi-Provider AI Support: OpenAI GPT-4, Anthropic Claude, Google Gemini, DeepSeek, OpenRouter, xAI Grok, Groq, and Z.ai
  - Configurable Reviewer Personas: Senior Engineer, Security Expert, Performance Specialist, Accessibility Advocate
  - Smart File Processing: Large file chunking, comprehensive exclusion patterns for all major development stacks (164+ patterns)
  - Discord Notifications: Real-time status updates for review start, completion, and errors with AI model information
  - GitHub Integration: Seamless PR commenting with inline and general review comments
  - Enterprise Ready: Secure credential management, rate limiting, comprehensive error handling, robust JSON parsing
  - Universal Compatibility: Works with any technology stack (Node.js, Python, Java, Flutter, .NET, Go, Rust, PHP, Ruby, etc.)

  🔧 **How it works:**
  1. PR Trigger: GitHub Actions workflow activates on pull request events
  2. Repository Checkout: Action checks out the target repository code
  3. File Analysis: System identifies changed files, applies comprehensive exclusion filters
  4. AI Processing: Code is chunked if needed and sent to configured AI model
  5. Review Generation: AI analyzes code using specified persona and generates comments
  6. Comment Posting: Inline and general comments posted to GitHub PR with AI model attribution
  7. Notification: Discord webhook sends status updates with AI model information (if configured)

  Example usage:

  ```yaml
  jobs:
    review:
      runs-on: ubuntu-latest
      steps:
        - uses: obiwancenovi/ai-code-reviewer@v1.0.17
          with:
            pr-number: ${{ github.event.pull_request.number }}
            repository: ${{ github.repository }}
            ai-persona: "senior-engineer"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
